version: '3'

services:
  web:
    build: .
    environment: 
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST: "postgres"
      FIXER_APIKEY: "dummy"
    ports:
      - "8080:8080"
      - "8081:8081"

    
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "54320:5432"
    volumes:
      - passbase_data:/var/lib/postgresql/data

volumes:
  passbase_data:
