CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = (NOW() AT TIME ZONE 'utc');
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;
