// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.6
// source: conversion.proto

package conversion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertAmountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputCurrency *string  `protobuf:"bytes,1,opt,name=input_currency,json=inputCurrency,proto3,oneof" json:"input_currency,omitempty"`
	Amount        *float32 `protobuf:"fixed32,2,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	OutputCurreny *string  `protobuf:"bytes,3,opt,name=output_curreny,json=outputCurreny,proto3,oneof" json:"output_curreny,omitempty"`
}

func (x *ConvertAmountRequest) Reset() {
	*x = ConvertAmountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conversion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountRequest) ProtoMessage() {}

func (x *ConvertAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountRequest.ProtoReflect.Descriptor instead.
func (*ConvertAmountRequest) Descriptor() ([]byte, []int) {
	return file_conversion_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertAmountRequest) GetInputCurrency() string {
	if x != nil && x.InputCurrency != nil {
		return *x.InputCurrency
	}
	return ""
}

func (x *ConvertAmountRequest) GetAmount() float32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *ConvertAmountRequest) GetOutputCurreny() string {
	if x != nil && x.OutputCurreny != nil {
		return *x.OutputCurreny
	}
	return ""
}

type ConvertAmountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount *float32 `protobuf:"fixed32,1,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
}

func (x *ConvertAmountResponse) Reset() {
	*x = ConvertAmountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conversion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountResponse) ProtoMessage() {}

func (x *ConvertAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountResponse.ProtoReflect.Descriptor instead.
func (*ConvertAmountResponse) Descriptor() ([]byte, []int) {
	return file_conversion_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertAmountResponse) GetAmount() float32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

var File_conversion_proto protoreflect.FileDescriptor

var file_conversion_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xbc,
	0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x0e, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0d, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x2a, 0x0a, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0d, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x79, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f,
	0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x79, 0x22, 0x3f, 0x0a,
	0x15, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x68,
	0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x74, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x6b, 0x6f, 0x66, 0x6f,
	0x77, 0x6f, 0x72, 0x6f, 0x6c, 0x61, 0x2f, 0x70, 0x62, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63,
	0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_conversion_proto_rawDescOnce sync.Once
	file_conversion_proto_rawDescData = file_conversion_proto_rawDesc
)

func file_conversion_proto_rawDescGZIP() []byte {
	file_conversion_proto_rawDescOnce.Do(func() {
		file_conversion_proto_rawDescData = protoimpl.X.CompressGZIP(file_conversion_proto_rawDescData)
	})
	return file_conversion_proto_rawDescData
}

var file_conversion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_conversion_proto_goTypes = []interface{}{
	(*ConvertAmountRequest)(nil),  // 0: conversion.ConvertAmountRequest
	(*ConvertAmountResponse)(nil), // 1: conversion.ConvertAmountResponse
}
var file_conversion_proto_depIdxs = []int32{
	0, // 0: conversion.ConversionService.CovertAmount:input_type -> conversion.ConvertAmountRequest
	1, // 1: conversion.ConversionService.CovertAmount:output_type -> conversion.ConvertAmountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_conversion_proto_init() }
func file_conversion_proto_init() {
	if File_conversion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_conversion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertAmountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conversion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertAmountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_conversion_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_conversion_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_conversion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conversion_proto_goTypes,
		DependencyIndexes: file_conversion_proto_depIdxs,
		MessageInfos:      file_conversion_proto_msgTypes,
	}.Build()
	File_conversion_proto = out.File
	file_conversion_proto_rawDesc = nil
	file_conversion_proto_goTypes = nil
	file_conversion_proto_depIdxs = nil
}
